language: generic

matrix:
  include:
    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - CTAPIPE_VERSION=master

    - os: linux
      python: 3.6
      env:
        - PYTHON_VERSION=3.6
        - CTAPIPE_VERSION=v0.6.2

    - os: linux
      python: 3.7
      env:
        - PYTHON_VERSION=3.7
        - CTAPIPE_VERSION=master

    - os: linux
      python: 3.7
      env:
        - PYTHON_VERSION=3.7
        - CTAPIPE_VERSION=v0.6.2


before_install:
    - export PYTHONIOENCODING=UTF8
    - export MPLBACKEND=Agg

    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - . $HOME/miniconda/etc/profile.d/conda.sh
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda  # get latest conda version
    - conda info -a # Useful for debugging any issues with conda

install:
    - conda create --name travis python=$PYTHON_VERSION
    - travis_wait 20 conda env update -n travis --file py${PYTHON_VERSION}_env.yaml
    - conda activate travis
    
    # we install ctapipe using pip to be able to select any commit, e.g. the current master
    - pip install https://github.com/cta-observatory/ctapipe/archive/$CTAPIPE_VERSION.tar.gz
    - pip install -e .

script:
    - pytest -v
